name: Codacy Security Scan

on:
  schedule:
    - cron: '25 6 * * 3'

permissions:
  contents: read
  security-events: write

jobs:
  codacy-security-scan:
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@562ee3e92b8e92df8b67e0a5ff8aa8e261919c08 # v4.4.7
        with:
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v4
        continue-on-error: true
        with:
          sarif_file: results.sarif
          category: codacy
